### ISSUE TITLE
Don't use no_cache param

### ISSUE THREAD

**Issue by gilbertsoft** [aimeos/aimeos-typo3-dist#1]
Remove no cache option from pages count, stock, suggest and update in initial page tree import.

What about existing installations? Perhaps an update script removing the flag from these pages should be written or a hint in the update instructions.

**Comment by aimeos** [comment]
The `no_cache` option shouldn't be used but is not forbidden and it doesn't matter if the URLs to the pages for JSON resp. plain text responses contains this option. I don't think we need to provide an script that removes the flag from the pages (and maybe do some harm in customized page trees).

**Comment by aimeos** [comment]
Change in commit  9dab7c8
