### ISSUE TITLE
constants.txt contents not generated on first install

### ISSUE THREAD

**Issue by rowild** [aimeos/aimeos-typo3-dist#11]
If I am not mistaken, the command `./vendor/bin/typo3 extension:activate aimeos_dist` should take care of installing the dependencies and generating the page tree of a aimeos distribution that was created via composer.

Reading through the `Setup` class and its process function, it should also generate the appropriate `constants.txt` contents, but this does not happen in the first step. Instead, the `aimeos_dist` extension has to uninstalled and then reinstalled again - then the `contstants.txt` is populated with the appropriate page uids.

Do I have to change my "install behaviour"? Or is the "uninstall-reinstall" step part of the setup nature of a distribution?

I use TYPO3 9.5.9 (composer installation) and aimeos_dist 19.4 on a php 7.2.22 environment.

EDIT:
Deactivating and activating `aimeos_dist` via the typo3 command line (`extension:deactivate` and `extension:activate`) does NOT update `constants.txt`.

**Comment by aimeos** [comment]
Don't think that `extension:activate` will fire the `hasInstalledExtensions` signal so your question might be more suited to a TYPO3 core developer:
https://github.com/aimeos/aimeos-typo3/blob/master/ext_tables.php#L68

Also, `extension:activate` won't install any dependencies because that's the task of composer.

**Comment by rowild** [comment]
What? Why not? Activating an extension via extension manager does take care of installing and activating dependencies, but extension:activate does NOT?
(Sorry, this is a question I should ask on TYPO3, but this confuses me a lot... I am closing anyway...)

**Comment by aimeos** [comment]
AFAIK, dependencies are only resolved during installation (not activation)
