### ISSUE TITLE
get Cannot assign string to property Aimeos\MShop\Customer\Manager\Typo3::$pid of type int after install

### ISSUE THREAD

**Issue by p-view** [aimeos/aimeos-typo3-dist#16]
Hi, 

when i will checkout i get this error.

```
in /html/typo3/typo3conf/ext/aimeos/Resources/Libraries/aimeos/ai-typo3/src/MShop/Customer/Manager/Typo3.php line 307
   * @param int TYPO3 page ID
   * @since 2016.10
   * @see mshop/customer/manager/group/typo3/pid-default
   */
  $this->pid = $context->config()->get( 'mshop/customer/manager/typo3/pid-default', 0 );


  $level = \Aimeos\MShop\Locale\Manager\Base::SITE_ALL;
  $level = $context->config()->get( 'mshop/customer/manager/sitemode', $level );
```

thx for advice

**Comment by aimeos** [comment]
What is the error? Do you have a stack trace?

**Comment by p-view** [comment]
is in Frontent. The log is 
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Cannot assign string to property Aimeos\MShop\Customer\Manager\Typo3::$pid of type int | TypeError thrown in file /html/typo3/typo3conf/ext/aimeos/Resources/Libraries/aimeos/ai-typo3/src/MShop/Customer/Manager/Typo3.php in line 307. Requested URL: https://pxxxx.mittwaldserver.info/checkout
i can send you logins via mail if you want. It`s a typo3 12 and a install via extension manager at mittwald.

**Comment by p-view** [comment]
is it a pid missing? can i setup this via constants?
mshop/customer/manager/typo3/pid-default

**Comment by aimeos** [comment]
TYPO3 enforces PHP strict mode in it's code and that may be applied to the Aimeos code too. This prevents implicit type conversions from string to int in this case.

We've added an explicit type conversion in the code and you can get the latest package using:
```
composer req aimeos/ai-typo3:2023.10.x-dev
```

**Comment by p-view** [comment]
thx, great
