### ISSUE TITLE
Title tag printed twice

### ISSUE THREAD

**Issue by gilbertsoft** [aimeos/aimeos-typo3-dist#3]
The title tag is printed twice, first from TYPO3 and second from Aimeos. The setting page.config.noPageTitle should be set to 2 in the ts setup (https://docs.typo3.org/typo3cms/TyposcriptReference/7.6/Setup/Config/Index.html#nopagetitle)

But generally disable it will lead in pages with no title if there's no Aimeos plugin on the page. So a new page type seems to be the easiest way to get this.

**Comment by aimeos** [comment]
According to the documentation its "config.noPageTitle" instead of "page.config.noPageTitle" or did I miss something?

This setting is already added in the catalog list and detail view:
https://github.com/aimeos/aimeos-typo3/blob/bf2cd40fda5efa6fe0693e8a546f3668eab4b524/Classes/Controller/CatalogController.php#L78

**Comment by gilbertsoft** [comment]
Both is possible, config is global for all pages, page.config for one page only (https://docs.typo3.org/typo3cms/TyposcriptReference/7.6/Setup/Page/Index.html#config)

Seems not to work in my setup, will test again...

**Comment by gilbertsoft** [comment]
I can confirm that this isn't a common issue. On the test site it works fine. Difference between test and live site is boostrap_package and realurl are newer on the test server. I will update the live site next weeks, will report again then...

**Comment by aimeos** [comment]
@gilbertsoft Did you find the source of your problem?

**Comment by gilbertsoft** [comment]
Not so far. We are still working on new products and after that will do the update. But since only the current prod site is affected, I think we could close this issue. If still something goes wrong after the update I can reopen it...
