### ISSUE TITLE
Install fails on TYPO3 8.6.1

### ISSUE THREAD

**Issue by gilbertsoft** [aimeos/aimeos-typo3-dist#4]
Message:
Could not install distribution 'bootstrap_package'
Your TYPO3 version is higher than this extension requires. It requires TYPO3 versions 7.6.2 - 8.5.99

bootstrap_package 7.0.5 supports version 8.6.1. I'm currently testing this combination...

**Comment by aimeos** [comment]
You patch is merged. Thanks a lot!

**Comment by gilbertsoft** [comment]
Welcome!
