### ISSUE TITLE
Logo is not shown

### ISSUE THREAD

**Issue by gilbertsoft** [aimeos/aimeos-typo3-dist#7]
Change ts constants to:
page.logo.height = 40
page.logo.width = 125

**Comment by aimeos** [comment]
Can you create a PR for this?

**Comment by gilbertsoft** [comment]
Yes, I can export my tree...

**Comment by gilbertsoft** [comment]
How do you create the data.t3d export? Do you have a preset? Are exports made in T3 8.6.x backward compatible or do I have to make an export from an T3 6.2.x version?

**Comment by aimeos** [comment]
The bootstrap_package for TYPO3 8 seems to overwrite the logo dimensions via CSS.The `height` and `width` parameter doesn't have any effect any more.

**Comment by aimeos** [comment]
Your suggested config has been added to the page tree nevertheless: https://github.com/aimeos/aimeos-typo3-dist/commit/f474c7dc01931d6b63e76c3b7f8d01492be80cdb

**Comment by gilbertsoft** [comment]
Version 8 was not available as I made the tests. But I think so we are compatible with versions 7 and 8 and that's better so far!
